### ISSUE TITLE
Error while cross compiling to Windows from MacOS

### ISSUE THREAD

**Issue by pascalporedda** [Hanaasagi/machine-uid#6]
Hey there,

since I updated the crate version to 0.4.0 I get the following error when invoking cargo build with the following flags

`cargo build --release --target x86_64-pc-windows-gnu` 

I'm using MacOS Ventura + the latest stable Rust toolchains.

```text
  = note: /opt/homebrew/Cellar/mingw-w64/11.0.0/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: target/x86_64-pc-windows-gnu/release/deps/libmachine_uid-298ed35685296eff.rlib(machine_uid-298ed35685296eff.machine_uid.1208bef349eb5abc-cgu.2.rcgu.o):machine_uid.1208be:(.text+0x54): undefined reference to `MachineUidIsWow64'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

I guess this was introduced via PR #4 .

My current solution is to simply downgrade to version 0.3.0.

**Comment by Hanaasagi** [comment]
OK, I tried cross-compiling on Linux and found the same issue. It seems that the `build.rs` was not executed, which resulted in the absence of the `MachineUidIsWow64` symbol being generated.

**Comment by Hanaasagi** [comment]
Hey, I think PR #7 could fix the cross-compiling problem. I'm using the [cross](https://github.com/cross-rs/cross) tool to test locally and it seems to work fine.


Could you try this? Thanks.


```toml
[dependencies]
machine-uid = { git = "https://github.com/Hanaasagi/machine-uid", branch = "fix-cross-build" }
```

**Comment by pascalporedda** [comment]
Just tried it, and it works like a charm 👍🏻

**Comment by Hanaasagi** [comment]
Thank you.
